name: "Test Current Repo Gction"
on:
  push:
    branches:
    - 'develop'
jobs:
  test_counter_servce_gaction:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        isNijiaApiService: [true,false]
    name: "Trigger test"
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Get counter value for key: ${{ github.event.repository.name }}"
        id: step_counter_service
        uses: SweetRainGarden/SrgCounterServiceGaction@develop
        with:
          keyName: ${{ github.event.repository.name }}
          apiKey: ${{ secrets.COUNTER_SERVICE_API_KEY }}
          apiDomain: ${{ secrets.COUNTER_SERVICE_API_DOMAIN }}
          isNijiaApiService: ${{ matrix.isNijiaApiService }}

      - name: "Echo counter value: ${{ steps.step_counter_service.outputs.gaction_output_counter_value }}"
        run: echo "The counter value is ${{ steps.step_counter_service.outputs.gaction_output_counter_value }}"
