name: "Test Current Repo Gaction"
on:
  push:
    branches:
    - 'develop'
    - 'randy/*'
jobs:
  test_counter_servce_gaction:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        isEnableNinjaApiService: [ false, true ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: "Get counter value for key: ${{ github.event.repository.name }}"
        id: step_counter_service
        uses: SweetRainGarden/SrgCounterServiceGaction@develop
        with:
          keyName: ${{ github.event.repository.name }}
          apiKey: ${{ secrets.COUNTER_SERVICE_API_KEY }}
          apiDomain: ${{ secrets.COUNTER_SERVICE_API_DOMAIN }}
          isNinjaApiService: ${{ matrix.isEnableNinjaApiService }}

      - name: "Echo counter value: ${{ steps.step_counter_service.outputs.gaction_output_counter_value }}"
        id: step_echo_output
        run: |
          echo "The key: ${{ github.event.repository.name }}'s counter value is ${{ steps.step_counter_service.outputs.gaction_output_counter_value }}"
          echo "counter_key=${{ github.event.repository.name }}"
          echo "counter_value=${{ steps.step_counter_service.outputs.gaction_output_counter_value }}"
